version: 1.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

    nuget restore -verbosity detailed

    appveyor-retry nuget restore

    dotnet restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
after_build:
- cmd: dotnet pack ./src/Serilog.Sinks.Slack.Core/ --output nupkgs
test: off
artifacts:
- path: '\nupkgs\Serilog.Sinks.Slack.Core.*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: vezTJ3PuB3zTp5IHFUDDL4kQm9NRXHeuBqQCVlfx1CbBBTHZ5iuLEbchqqGTeFQ+
  skip_symbols: true
notifications:
- provider: Slack
  incoming_webhook:
    secure: FgB39fbzhvs/r/8gzaohtkaZRVB/UPV9a2lI80V+ZjgvB19qih716qcKbuZGBDgIzFfkBXxSVjNqbc3tUXt07fbOoBPNWsVtijXpr4+BIF4=
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false