version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
configuration: Release
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

    nuget restore -verbosity detailed

    appveyor-retry nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: vezTJ3PuB3zTp5IHFUDDL4kQm9NRXHeuBqQCVlfx1CbBBTHZ5iuLEbchqqGTeFQ+
  skip_symbols: false
notifications:
- provider: Slack
  auth_token:
    secure: q0TDncVz8udzeG+E903TpQ/+QBa17EahyfIcjr4uJDnvazhuPFzPLbAPoXfZrluP6RSJ9u7MPVL1qZbbVu1qcA==
  channel: appveyorbuilds
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false